"""Add concussion-specific fields and symptom tracking

Revision ID: 77755d3d64ec
Revises: 8dbc207da801
Create Date: 2026-01-11 00:45:14.801979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77755d3d64ec'
down_revision = '8dbc207da801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concussion_symptom_scores',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('injury_id', sa.String(length=50), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('assessed_by', sa.String(length=100), nullable=True),
    sa.Column('headache', sa.Integer(), nullable=True),
    sa.Column('pressure_in_head', sa.Integer(), nullable=True),
    sa.Column('neck_pain', sa.Integer(), nullable=True),
    sa.Column('nausea_vomiting', sa.Integer(), nullable=True),
    sa.Column('dizziness', sa.Integer(), nullable=True),
    sa.Column('blurred_vision', sa.Integer(), nullable=True),
    sa.Column('balance_problems', sa.Integer(), nullable=True),
    sa.Column('sensitivity_to_light', sa.Integer(), nullable=True),
    sa.Column('sensitivity_to_noise', sa.Integer(), nullable=True),
    sa.Column('feeling_slowed_down', sa.Integer(), nullable=True),
    sa.Column('feeling_mental_fog', sa.Integer(), nullable=True),
    sa.Column('difficulty_concentrating', sa.Integer(), nullable=True),
    sa.Column('difficulty_remembering', sa.Integer(), nullable=True),
    sa.Column('fatigue_low_energy', sa.Integer(), nullable=True),
    sa.Column('confusion', sa.Integer(), nullable=True),
    sa.Column('drowsiness', sa.Integer(), nullable=True),
    sa.Column('trouble_falling_asleep', sa.Integer(), nullable=True),
    sa.Column('more_emotional', sa.Integer(), nullable=True),
    sa.Column('irritability', sa.Integer(), nullable=True),
    sa.Column('sadness', sa.Integer(), nullable=True),
    sa.Column('nervous_anxious', sa.Integer(), nullable=True),
    sa.Column('feeling_like_in_a_fog', sa.Integer(), nullable=True),
    sa.Column('total_symptom_score', sa.Integer(), nullable=True),
    sa.Column('orientation_score', sa.Integer(), nullable=True),
    sa.Column('immediate_memory_score', sa.Integer(), nullable=True),
    sa.Column('concentration_score', sa.Integer(), nullable=True),
    sa.Column('balance_score', sa.Integer(), nullable=True),
    sa.Column('tandem_gait_time', sa.Float(), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['injury_id'], ['injury_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('injury_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_concussion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('loss_of_consciousness', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('loc_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('post_traumatic_amnesia', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pta_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mechanism_of_concussion', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('suspected_concussion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('referred_to_physician', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('physician_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('physician_contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('rtp_protocol_started', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rtp_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rtp_stage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rtp_stage_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rtp_completed_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rtp_medical_clearance', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rtp_medical_clearance_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rtp_medical_clearance_by', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('injury_records', schema=None) as batch_op:
        batch_op.drop_column('rtp_medical_clearance_by')
        batch_op.drop_column('rtp_medical_clearance_date')
        batch_op.drop_column('rtp_medical_clearance')
        batch_op.drop_column('rtp_completed_date')
        batch_op.drop_column('rtp_stage_start_date')
        batch_op.drop_column('rtp_stage')
        batch_op.drop_column('rtp_start_date')
        batch_op.drop_column('rtp_protocol_started')
        batch_op.drop_column('physician_contact')
        batch_op.drop_column('physician_name')
        batch_op.drop_column('referred_to_physician')
        batch_op.drop_column('suspected_concussion')
        batch_op.drop_column('mechanism_of_concussion')
        batch_op.drop_column('pta_duration')
        batch_op.drop_column('post_traumatic_amnesia')
        batch_op.drop_column('loc_duration')
        batch_op.drop_column('loss_of_consciousness')
        batch_op.drop_column('is_concussion')

    op.drop_table('concussion_symptom_scores')
    # ### end Alembic commands ###
