"""Add complete models for Phase 2

Revision ID: 8dbc207da801
Revises: 2d5d63e130e2
Create Date: 2026-01-08 02:26:36.343287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbc207da801'
down_revision = '2d5d63e130e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaches',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('injury_records',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('athlete_id', sa.String(length=50), nullable=False),
    sa.Column('injury_type', sa.String(length=100), nullable=False),
    sa.Column('body_part', sa.String(length=100), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('date_reported', sa.Date(), nullable=False),
    sa.Column('date_occurred', sa.Date(), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('estimated_recovery_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('clearance_date', sa.Date(), nullable=True),
    sa.Column('clearance_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_tests',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('athlete_id', sa.String(length=50), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('bench_press_1rm', sa.Float(), nullable=True),
    sa.Column('squat_1rm', sa.Float(), nullable=True),
    sa.Column('deadlift_1rm', sa.Float(), nullable=True),
    sa.Column('pull_ups_max', sa.Integer(), nullable=True),
    sa.Column('push_ups_1min', sa.Integer(), nullable=True),
    sa.Column('sit_ups_2min', sa.Integer(), nullable=True),
    sa.Column('sprint_10m', sa.Float(), nullable=True),
    sa.Column('sprint_20m', sa.Float(), nullable=True),
    sa.Column('sprint_40m', sa.Float(), nullable=True),
    sa.Column('agility_t_test', sa.Float(), nullable=True),
    sa.Column('agility_505', sa.Float(), nullable=True),
    sa.Column('illinois_agility', sa.Float(), nullable=True),
    sa.Column('vertical_jump', sa.Float(), nullable=True),
    sa.Column('broad_jump', sa.Float(), nullable=True),
    sa.Column('single_leg_jump_left', sa.Float(), nullable=True),
    sa.Column('single_leg_jump_right', sa.Float(), nullable=True),
    sa.Column('yo_yo_test', sa.Float(), nullable=True),
    sa.Column('bronco_test', sa.Float(), nullable=True),
    sa.Column('sit_and_reach', sa.Float(), nullable=True),
    sa.Column('dorsiflexion_left', sa.Float(), nullable=True),
    sa.Column('dorsiflexion_right', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wellness_entries',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('athlete_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('muscle_soreness', sa.Integer(), nullable=True),
    sa.Column('nutrition_quality', sa.Integer(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('motivation_level', sa.Integer(), nullable=True),
    sa.Column('previous_session_rpe', sa.Integer(), nullable=True),
    sa.Column('previous_session_duration', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jersey_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('dominant_side', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('injury_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('medical_notes', sa.Text(), nullable=True))

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('season')

    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.drop_column('medical_notes')
        batch_op.drop_column('injury_history')
        batch_op.drop_column('dominant_side')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('jersey_number')

    op.drop_table('wellness_entries')
    op.drop_table('performance_tests')
    op.drop_table('injury_records')
    op.drop_table('coaches')
    # ### end Alembic commands ###
