"""Add workload and recovery models

Revision ID: fb43dbe2f11e
Revises: 77755d3d64ec
Create Date: 2026-01-20 12:55:46.344956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb43dbe2f11e'
down_revision = '77755d3d64ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prehab_recommendations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('athlete_id', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('recommendation_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('body_parts', sa.String(length=200), nullable=True),
    sa.Column('focus_area', sa.String(length=100), nullable=True),
    sa.Column('exercises', sa.Text(), nullable=False),
    sa.Column('frequency_per_week', sa.Integer(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('compliance_rate', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_sessions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('athlete_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('recovery_type', sa.String(length=50), nullable=False),
    sa.Column('session_name', sa.String(length=100), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('stretching', sa.Boolean(), nullable=True),
    sa.Column('foam_rolling', sa.Boolean(), nullable=True),
    sa.Column('massage', sa.Boolean(), nullable=True),
    sa.Column('ice_bath', sa.Boolean(), nullable=True),
    sa.Column('compression', sa.Boolean(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('nutrition_quality', sa.Integer(), nullable=True),
    sa.Column('hydration_status', sa.Integer(), nullable=True),
    sa.Column('prehab_exercises', sa.Text(), nullable=True),
    sa.Column('perceived_recovery', sa.Integer(), nullable=True),
    sa.Column('readiness_improvement', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workload_sessions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('athlete_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('session_name', sa.String(length=100), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('perceived_exertion', sa.Integer(), nullable=False),
    sa.Column('workload_score', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('average_hr', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('sprints_count', sa.Integer(), nullable=True),
    sa.Column('high_intensity_distance', sa.Float(), nullable=True),
    sa.Column('fatigue_level', sa.Integer(), nullable=True),
    sa.Column('muscle_soreness_post', sa.Integer(), nullable=True),
    sa.Column('motivation_post', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workload_sessions')
    op.drop_table('recovery_sessions')
    op.drop_table('prehab_recommendations')
    # ### end Alembic commands ###
